---
name: Text-Undiacritic
version: 0.02
author:
  - 'Helmut Wollmersdorfer C<< <WOLLMERS@cpan.org> >>'
abstract: change characters with diacritics into their base character
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Exporter: 0
  Unicode::Normalize: 0
  charnames: 0
  version: 0
build_requires:
  English: 0
  File::Basename: 0
  File::Find: 0
  Test::Exception: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Text::Undiacritic:
    file: lib/Text/Undiacritic.pm
    version: v0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  namespace: Text::Undiacritic
